# Generated by Django 4.2.3 on 2023-09-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
