# Generated by Django 4.2.3 on 2023-09-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerk',
            name='user',
        ),
    ]
